sulu_media:
    storage: s3
    storages:
        s3:
            key: '%env(resolve:AWS_S3_KEY)%'
            secret: '%env(resolve:AWS_S3_SECRET)%'
            bucket_name: '%env(resolve:AWS_S3_BUCKET_NAME)%'
            region: '%env(resolve:AWS_S3_REGION)%'